[build-system]
requires = ['cython', 'numpy', 'setuptools<=75.7.0']
build-backend = 'setuptools.build_meta'

[tool.setuptools]
package-dir = {'' = 'src'}

[tool.setuptools.packages.find]
where = ['src']

[project]
name = 'MuonDataLib'
version = "0.9.0b2"
requires-python = ">=3.7.1"
dependencies = ['numpy', 'h5py', 'plotly', 'cython']
authors = [{name='Anthony Lim', email='anthony.lim@stfc.ac.uk'}]
description = "A Bayesian fitting package used for model selection and grid searches of fits for neutron and muon data."
keywords=['bayesian', 'fitting', 'QENS', 'muons']
readme = 'README.md'
license = {text = 'BSD'}

[project.optional-dependencies]
docs = ["sphinx==7.3.7",
	'jupyter-book',
        "nbsphinx==0.9.4"]

[project.urls]
Homepage = "https://quickbayes.readthedocs.io/en/latest/"
Documentation = "https://quickbayes.readthedocs.io/en/latest/"
Repository = 'https://github.com/ISISNeutronMuon/quickBayes'
